### PR TITLE
champi panel rework

### PR DESCRIPTION
**Pull request by Willster419**
This is a  re-work of champi's `playersPanelPro` mod.

The major re-work was to re-order and re-work the patches to behave like safeShot: There's a patch to disable as much as possible (attached), and the multi check options enable different features

You now can select the following:
alt text

Please run some installations, make sure
- there are no patch errors
- game loads up and you can configure from login screen
- a couple of them work in the game

Thanks guys!

### CODE REVIEW

**Comment by Willster419** [comment]
P.S. - You can use the beta database and select this branch

**Comment by Arkhorse** [comment]
Text mode and key mode need to be multi

**Comment by Willster419** [comment]
you mean "text format"?

these are required options by the mod. Yes, it's set by the mod by default, but you can't have team hp pools without any text, for example.

I could see them becomming multi if they were re-worded to be "change...", and the child package had (default).

Thoughts?

**Comment by Arkhorse** [comment]
If they are single1, only one of them can be selected, even though both are required. And yes, text format........

**Comment by Willster419** [comment]
🤦‍♂️ right. This is why we open reviews

**Comment by Willster419** [comment]
I just fixed it:

image

**Comment by Willster419** [comment]
`Ingame_Info_PlayersPanelPro_TeamHPPoolsBar` only enables the HP pools, and does not touch the bars. I installed with only selecting champi, and this was the result:

image

**Comment by Arkhorse** [comment]
Bars = tank HP pools, Pool = total team health

**Pull request merged**
